java_install_dir: "/usr/lib/jvm"
java_version: "17.0.10"

# Example URL (aapke according change ho sakta hai)
java_tar_name: "jdk-{{ java_version }}_linux-x64_bin.tar.gz"
java_download_url: "https://download.oracle.com/java/17/archive/{{ java_tar_name }}"

java_folder_name: "jdk-{{ java_version }}"
java_home: "{{ java_install_dir }}/{{ java_folder_name }}"
